### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Alphaplo** [unrealgt/unrealgt#1]
Hello, I can not successfully install the plugin to project, there are many errors when I build it. The instruction at homepage is too simple. Can you give more information? Thank you

**Comment by lolleko** [comment]
Can you provide some additional information:

UE4 version
Which steps did you attemp?
OS
Compiler

**Comment by Alphaplo** [comment]
I use WIN10, UE4.24 and VS2017.
I created a new plugin in the project and Clone the repository into the project plugin directory. Because my project is a blueprint project, I created a C++ class to create source directory, then I generated VS project files. The structure of the vs solution is 
<img width="180" alt="捕获" src="https://user-images.githubusercontent.com/49438755/77973295-fcac6f80-72f3-11ea-8b27-10e67b0fa370.PNG">
I am not sure about how to edit UNrealGT.build.cs, personally I put all include paths in variable PublicIncludePaths.
The build output is shown
<img width="458" alt="捕获2" src="https://user-images.githubusercontent.com/49438755/77974090-6ded2200-72f6-11ea-9c02-6284b4037f63.PNG">

**Comment by lolleko** [comment]
Okay, the problem is that since 4.24 Unreal now emits compilation errors instead of warnings. I think I can get this fixed til the end of the week.

In the meantime you can either fix the issues yourself (e.g add `#pragma once` to GTDataGeneratorComponent.h) or use an older unreal version (4.21/4.22) should definitely work.

**Comment by Alphaplo** [comment]
Hello, the same errors occur when I tried the UE version 4.22. In addition, #pragma once is already included in GTDataGeneratorComponent.h. I have no idea about it.

**Comment by lolleko** [comment]
Fixed the plugin for 4.24 in 692d700 (latest master). Let me know if this resolves your issue.

I currently don't have the time to develop the plugin / improve the docs. So feel free to ask me questions if you run into problems.

**Comment by Alphaplo** [comment]
Thanks for your help, I will try the latest version when I get some free space of my computer for downloading UE4.24. I have a problem about my project, whose objective is to generate instance segmentation masks for deep learning. The UE project Redwood is a forest environment containing InstancedFoliageActor. I'd like to get RGB images and their instance segmentation images for trees(a color for each tree), but since all trees are in InstancedFoliageActor, UE4 will consider them as an actor. Is there a way to get each component? I'm not very clear about relationship between classes in UE4, is InstancedFoliageActor a sub class in the actors contained in FGTObjectFilter?

**Comment by lolleko** [comment]
InstancedFoliageActor is a subclass of actor and could be used in FGTObjectFilter, but the InstancedFoliageActor does not only contain a single tree it contains all trees, to render them more efficiently.

The segmentation implementation is based on the stencil  buffer, which basically assigns a number to each mesh being drawn. Sadly Instance meshes can not be coloured separately, because all instances of a mesh are rendered with a single/the same draw call.

As far as I know all tools that can generate datasets via UE4 use the stencil buffer method.
At least at the time when I was working on unrealgt.
Feel free to check for yourself: https://github.com/microsoft/AirSim, https://github.com/NVIDIA/Dataset_Synthesizer, https://github.com/unrealcv/unrealcv, https://github.com/carla-simulator/carla

One possible solution is to get/create a basic environment place the trees yourself, as separate actors. There is a simple actor scatter tool in the UnrealGT plugin called AGTRandomObjectPlacer,
you can drag that into scene and select a few meshes/trees that will be placed randomly in the scene. If you use that actor make sure `bPlaceMeshActors` is checked otherwise it will youse instanced meshes aswell. 

After that you have two options:

Give each tree actor/component a custom tag (ideally you extend tin AGTRandomObjectPlacer that will set a component tag on each spawned mesh). And then assign the tag to a color in the filter list of GTSegmentationGeneratorComponent (Ideally you would do this by script aswell).

or

You can use the bColorEachComponentDifferent option on the segmentation generator (which is currently not exposed 👎 ). I might patch that in the next days if I have time. If you can't wait you can do it yourself by changing the second parameter in the SegmentationSetup call to true:
https://github.com/unrealgt/unrealgt/blob/master/Source/UnrealGT/Private/Generators/Image/GTSegmentationGeneratorComponent.cpp#L16

The downside of the second options is that the segmentation is limited to 255 colours (stencil buffer uses 8bit), these get distributed  randomly if there are more than 256 meshes but you still might get some overlap where two trees have the same color in a segmentation map.

In addition this will color every actor on the map not only trees, which might not be what you want.
If I get the patch in I might add an option that allows you to set an optional FGTObjectFilter  that will be used in conjunction with bColorEachComponentDifferent.

**Comment by Alphaplo** [comment]
Thank for your suggestion, it is very useful and suggestive. I have considered placing the trees myself, I will give a try.

**Comment by Alphaplo** [comment]
There is one point that I don't junderstand, since you said UnrealGT uses stencil buffer to generate segmentation and it is limited to 256 colors. How can I get  more than 256 meshes by first method you said?

**Comment by lolleko** [comment]
You can't: the limitation applies to both methods (manual and random distribution). You can only distribute 255 colors. This means you can only have 255 <Filter, Color> Pairs in the SegmentationGenerator.

But you can give multiple meshes the same color. So you can try to manually tag the actors in a way that minimises the chance of two meshes  that have the same stencil value overlapping (appearing next two each other on the screen). 

The random option will also assign multiple meshes the same color.
