### ISSUE TITLE
Is a manual trigger available

### ISSUE THREAD

**Issue by Mothershadowninja** [unrealgt/unrealgt#12]
I am trying to generate data for AI using UnrealGT. Now the generator starts immediately after the game start. Unfortunately I can't find anything on the website under Trigger. Is there a trigger available with which I can start and stop the generation myself. 

Hope I find a solution to my problem

**Comment by lolleko** [comment]
The only avaialbe trigger is a timed trigger: UGTTimedGeneratorTrigger which excutes the connected generators at a fixed interval. (Like in the tutorial https://unrealgt.github.io/basics/getting-started/)

You can easily add your custom triggers jsut have a look how the TimedTrigger is implemted: https://github.com/unrealgt/unrealgt/blob/master/Source/UnrealGT/Private/Triggers/GTTimedGeneratorTrigger.cpp

**Comment by tha-carta** [comment]
@Mothershadowninja I had a similar use case to what you described, needing to trigger on more generic game events. Take a look at PR #15. If you use the `GTGeneratorTrigger` base class, you'll have the flexibility you need using Blueprints.

If you need ground truth at very particular event times, you can call `Trigger` directly on those events. If you want manual control, you can make those events keyboard presses, as you'll see in the example on that PR. I think what you described in your post is starting and stopping a timed trigger manually; in this case you'll set up keypress events that start/stop a looping blueprint timer, which calls `Trigger` on the new base class.

Hope this helps, feel free to ping me if what I'm describing isn't clear!

**Comment by Mothershadowninja** [comment]
Hey @tha-carta  thanks for your awnser. 
Thats was what i was looking for. I must use pull the newstest Version from github rigth, to make it work ? 

Beaucse with UE 4.27.2 i can't install the new version anymore. 
I get got these threee error messages: 

/Plugins/unrealgt-master/Source/UnrealGT/Private/Generators/Image/GTSceneCaptureComponent2D.cpp(217): error C2039: 'GetPlatformData': is not a member of 'UTexture2D'
Plugins\unrealgt-master\Source\UnrealGT\Public\Generators/Image/GTSceneCaptureComponent2D.h(15): note: see declaration of 'UTexture2D'
Plugins/unrealgt-master/Source/UnrealGT/Private/Generators/Image/GTSceneCaptureComponent2D.cpp(217): error C2530: 'Mip': references must be initialized

Thanks for help

**Comment by lolleko** [comment]
This is most likely an issue with the changes I made to support UE5.
I thought `GetPlatformData()` & `GetResource()` already existed in 4.27 as well, guess I was wrong.

Try reverting these lines:

https://github.com/unrealgt/unrealgt/commit/b2e787d592c761214eb10cc9df9df9fe562ec2af#diff-b9313e81990f8bca927a3b425ba7e6cae3f589bd3d84fd3f92b72410dd0bcc69R112

 https://github.com/unrealgt/unrealgt/commit/b2e787d592c761214eb10cc9df9df9fe562ec2af#diff-766a3695e7a121dc8854c136f53d56107cf2976e6c50f80df7b3c502d2433ac0R217

https://github.com/unrealgt/unrealgt/commit/b2e787d592c761214eb10cc9df9df9fe562ec2af#diff-b9313e81990f8bca927a3b425ba7e6cae3f589bd3d84fd3f92b72410dd0bcc69R112

I will try to add a more permanent fix to maintain 4.27 compatibilty.

**Comment by Mothershadowninja** [comment]
Thanks for the help. Will try

**Comment by Mothershadowninja** [comment]
@tha-carta Hey i now upgradet now to 5.0.3 and use the newst version. How did get the trigger node. i can't replacte your exemple. Sorry for bouder you with this question. But thx for the help.

**Comment by tha-carta** [comment]
> @tha-carta Hey i now upgradet now to 5.0.3 and use the newst version. How did get the trigger node. i can't replacte your exemple. Sorry for bouder you with this question. But thx for the help.

@Mothershadowninja Have you gone through all of the install steps in the documentation? If this repo is in your project plugins directory, you should be able to build, regenerate project files, and open to use the new trigger BlueprintCallable function.

I have seen [some chatter](https://gamedev.stackexchange.com/questions/201654/blueprintcallable-functions-not-appearing-in-blueprint-ue5/201725?noredirect=1#comment367143_201725) about a possible bug in UE5 that requires you to delete the `Intermediate` and `Binaries` folders in order to get the build to pick up the changes. If the regular install doesn't work, maybe repeat the same install steps, but make sure those folders are deleted before you start. I could see this being an issue if you upgraded this repo with a git fetch/merge/pull, as opposed to a fresh clone.

**Comment by Mothershadowninja** [comment]
Okay will try it again thx for help.

**Comment by Mothershadowninja** [comment]
@tha-carta  Sorry to boder you again. I manged to get the note now. Must i change some settings? Because i rebuild your soulation and it still start as the game and not on my button press. Again thx for the help.

**Comment by tha-carta** [comment]
> @tha-carta  Sorry to boder you again. I manged to get the note now. Must i change some settings? Because i rebuild your soulation and it still start as the game and not on my button press. Again thx for the help.  

@Mothershadowninja can you post some screenshots of the blueprint you're working with? That would help me see what's going wrong.

Off the top of my head, my guess is that you might still be using the GTTimedGeneratorTrigger instead of the GTGeneratorTrigger?

Another thing to check is whether you're enabling control inputs from the correct PlayerController when game begins. If you do it the way I did it, you have to click on the game window after you start the game so it's focused, otherwise the keyboard input doesn't trigger.
